Repository aceleradora-TW/acelera-mais-front, pull requests merged in 2022-02, with the labels that each got.

#80 66/implementar i18n exercise
  src/pages/exercises/components/exercises-list/index.js
  src/pages/exercises/index.js
  src/utils/i18next/languages/en/common.json
  src/utils/i18next/languages/pt/common.json
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#81 72/feat novo visual componente modal
  src/components/buttons/button/styled.js
  src/components/modal/style.js
Labels: melhorias, Nv: Fácil, FRONT-END

#82 feat(components/inputs): altera estilo dos inputs texto e data
  src/components/inputs/styled.js
Labels: melhorias, Nv: Fácil, FRONT-END

#83 132/refact trocar dominio exercise para challenge
  src/pages/challenges/components/challenges-list/index.js
  src/pages/challenges/components/challenges-list/styled.js
  src/pages/challenges/components/toggle-row/index.js
  src/pages/challenges/components/toggle-row/styled.js
  src/pages/challenges/components/toggle-row/togglerow.stories.jsx
  src/pages/challenges/index.js
  src/pages/evaluation/components/answer/answer.js
  src/pages/evaluation/components/select-note/select-note.js
  src/pages/evaluation/components/select-type/select-type.js
  src/pages/evaluation/index.js
  src/pages/exercises/components/exercises-list/index.js
  src/pages/hiring-process/adapter/hiring-process-adapter.js
  src/pages/hiring-process/components/hiring-process-list/index.js
  src/routes/index.js
  src/utils/i18next/languages/en/common.json
  src/utils/i18next/languages/pt/common.json
Labels: Nv: Médio, refatorar, FRONT-END
