Repository aceleradora-TW/acelera-mais-front, pull requests merged in 2022-01, with the labels that each got.

#36 28/implementar feature toggle e remover regras de css que escondem os elementos
  src/components/hiring-process-list/index.js
  src/components/hiring-process-list/process-list.css
  src/feature-toggle/index.js
  src/pages/exercises/index.js
  src/pages/hiring-process/index.js
  src/pages/hiring-process/style.css
Labels: FRONT-END

#37 33/refact: mover componentes para Exercise Page
  src/pages/exercises/components/exercises-list/index.js
  src/pages/exercises/components/exercises-list/style.css
  src/pages/exercises/components/toggle-row/index.js
  src/pages/exercises/components/toggle-row/style.css
  src/pages/exercises/components/toggle-row/togglerow.stories.jsx
  src/pages/exercises/index.js
Labels: melhorias, Nv: Fácil, refatorar, FRONT-END

#39 35/mover componentes exclusivos para página de authentication
  src/components/is-auth/index.js
  src/pages/authentication/forms/login/index.js
  src/pages/authentication/forms/login/login.stories.jsx
  src/pages/authentication/forms/login/style.css
  src/pages/authentication/index.js
  src/routes/index.js
Labels: melhorias, Nv: Fácil, refatorar, FRONT-END

#49 31/refact: Componentizacao da página de Avaliação (evaluation)
  src/pages/evaluation/components/answer/answer.js
  src/pages/evaluation/components/header/header.js
  src/pages/evaluation/components/select-note/select-note.js
  src/pages/evaluation/components/select-type/select-type.js
  src/pages/evaluation/index.js
Labels: refatorar, FRONT-END

#55 44/refact components status
  src/components/status/index.js
  src/components/status/status.css
  src/components/status/styles.js
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#56 43/components/select
  src/components/select/index.js
  src/components/select/select.css
  src/components/select/select.js
  yarn.lock
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#67 47/refact pages exercises list toggle row
  src/pages/exercises/components/exercises-list/index.js
  src/pages/exercises/components/toggle-row/index.js
  src/pages/exercises/components/toggle-row/style.css
  src/pages/exercises/components/toggle-row/styled.js
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#69 refactor: unificando o codigo das tabelas
  src/components/buttons/button/styled.js
  src/components/status/styles.js
  src/components/table/table.js
  src/components/table/table.stories.jsx
  src/components/toggle-row/index.js
  src/index.css
  src/index.js
  src/mocks/exercise-mock.json
  src/pages/evaluation/components/answer/answer.js
  src/pages/evaluation/index.js
  src/pages/evaluation/styled.js
  src/pages/exercises/components/exercises-list/index.js
  src/pages/exercises/components/exercises-list/styled.js
  src/pages/exercises/components/toggle-row/styled.js
  src/pages/exercises/index.js
  src/pages/hiring-process/adapter/hiring-process-adapter.js
  src/pages/hiring-process/components/hiring-process-list/index.js
  src/pages/hiring-process/components/hiring-process-list/styles.js
  src/pages/hiring-process/components/import-google-sheet/index.js
  src/pages/hiring-process/index.js
  src/setupTests.js
  src/utils/feature-toggle/index.js
  src/utils/i18next/index.js
  src/utils/i18next/languages/en/common.json
  src/utils/i18next/languages/pt/common.json
  src/utils/isAdmin/index.js
Labels: melhorias, Nv: Difícil, refatorar, FRONT-END

#54 feat(components/modal): implementa styled components
  src/components/modal/index.js
  src/components/modal/style.js
  src/pages/evaluation/styled.js
  src/pages/hiring-process/style.css
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#73 70/bug botão de avaliar perdeu seu estilo na refatoração
  src/components/select/select.js
  src/pages/evaluation/index.js
  src/pages/evaluation/styled.js
Labels: bug, melhorias, Nv: Médio, FRONT-END

#74 61/refact implementar internacionalização i18next em pages/hiring process list/import google sheet
  src/pages/hiring-process/components/import-google-sheet/index.js
  src/utils/i18next/languages/en/common.json
  src/utils/i18next/languages/pt/common.json
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#76 64/implementar pagina de exercicios i18n
  src/components/status/index.js
  src/pages/exercises/components/toggle-row/index.js
  src/utils/i18next/languages/en/common.json
  src/utils/i18next/languages/pt/common.json
Labels: melhorias, Nv: Médio, refatorar, FRONT-END

#79 65/implementar pages evaluation i18next
  src/pages/evaluation/components/answer/answer.js
  src/pages/evaluation/components/header/header.js
  src/pages/evaluation/components/select-note/select-note.js
  src/pages/evaluation/components/select-type/select-type.js
  src/pages/evaluation/index.js
  src/utils/i18next/languages/en/common.json
  src/utils/i18next/languages/pt/common.json
Labels: melhorias, Nv: Médio, refatorar, FRONT-END
